/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: C:\Users\Marko\Documents\Development\morus_fuel_sensor\morus_uavcan_msgs\control\position_control\2052.PoseVelocity.uavcan
 */

#ifndef MORUS_UAVCAN_MSGS_CONTROL_POSITION_CONTROL_POSEVELOCITY_HPP_INCLUDED
#define MORUS_UAVCAN_MSGS_CONTROL_POSITION_CONTROL_POSEVELOCITY_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

#include <morus_uavcan_msgs\common\Pose.hpp>
#include <morus_uavcan_msgs\common\Twist.hpp>
#include <uavcan\Timestamp.hpp>

/******************************* Source text **********************************
#
# Message for getting position of UAV
#

uavcan.Timestamp	timestamp

morus_uavcan_msgs.common.Pose 	pose
morus_uavcan_msgs.common.Twist 	velocity
******************************************************************************/

/********************* DSDL signature source definition ***********************
morus_uavcan_msgs.control.position_control.PoseVelocity
uavcan.Timestamp timestamp
morus_uavcan_msgs.common.Pose pose
morus_uavcan_msgs.common.Twist velocity
******************************************************************************/

#undef timestamp
#undef pose
#undef velocity

namespace morus_uavcan_msgs
{
namespace control
{
namespace position_control
{

template <int _tmpl>
struct UAVCAN_EXPORT PoseVelocity_
{
    typedef const PoseVelocity_<_tmpl>& ParameterType;
    typedef PoseVelocity_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::Timestamp timestamp;
        typedef ::morus_uavcan_msgs::common::Pose pose;
        typedef ::morus_uavcan_msgs::common::Twist velocity;
    };

    enum
    {
        MinBitLen
            = FieldTypes::timestamp::MinBitLen
            + FieldTypes::pose::MinBitLen
            + FieldTypes::velocity::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::timestamp::MaxBitLen
            + FieldTypes::pose::MaxBitLen
            + FieldTypes::velocity::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::timestamp >::Type timestamp;
    typename ::uavcan::StorageType< typename FieldTypes::pose >::Type pose;
    typename ::uavcan::StorageType< typename FieldTypes::velocity >::Type velocity;

    PoseVelocity_()
        : timestamp()
        , pose()
        , velocity()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<472 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 2052 };

    static const char* getDataTypeFullName()
    {
        return "morus_uavcan_msgs.control.position_control.PoseVelocity";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool PoseVelocity_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        timestamp == rhs.timestamp &&
        pose == rhs.pose &&
        velocity == rhs.velocity;
}

template <int _tmpl>
bool PoseVelocity_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(timestamp, rhs.timestamp) &&
        ::uavcan::areClose(pose, rhs.pose) &&
        ::uavcan::areClose(velocity, rhs.velocity);
}

template <int _tmpl>
int PoseVelocity_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::timestamp::encode(self.timestamp, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::pose::encode(self.pose, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::velocity::encode(self.velocity, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int PoseVelocity_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::timestamp::decode(self.timestamp, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::pose::decode(self.pose, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::velocity::decode(self.velocity, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature PoseVelocity_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x280DF9B5F71BB094ULL);

    FieldTypes::timestamp::extendDataTypeSignature(signature);
    FieldTypes::pose::extendDataTypeSignature(signature);
    FieldTypes::velocity::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef PoseVelocity_<0> PoseVelocity;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::morus_uavcan_msgs::control::position_control::PoseVelocity > _uavcan_gdtr_registrator_PoseVelocity;

}

} // Namespace position_control
} // Namespace control
} // Namespace morus_uavcan_msgs

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::morus_uavcan_msgs::control::position_control::PoseVelocity >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::morus_uavcan_msgs::control::position_control::PoseVelocity::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::morus_uavcan_msgs::control::position_control::PoseVelocity >::stream(Stream& s, ::morus_uavcan_msgs::control::position_control::PoseVelocity::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "timestamp: ";
    YamlStreamer< ::morus_uavcan_msgs::control::position_control::PoseVelocity::FieldTypes::timestamp >::stream(s, obj.timestamp, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "pose: ";
    YamlStreamer< ::morus_uavcan_msgs::control::position_control::PoseVelocity::FieldTypes::pose >::stream(s, obj.pose, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "velocity: ";
    YamlStreamer< ::morus_uavcan_msgs::control::position_control::PoseVelocity::FieldTypes::velocity >::stream(s, obj.velocity, level + 1);
}

}

namespace morus_uavcan_msgs
{
namespace control
{
namespace position_control
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::morus_uavcan_msgs::control::position_control::PoseVelocity::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::morus_uavcan_msgs::control::position_control::PoseVelocity >::stream(s, obj, 0);
    return s;
}

} // Namespace position_control
} // Namespace control
} // Namespace morus_uavcan_msgs

#endif // MORUS_UAVCAN_MSGS_CONTROL_POSITION_CONTROL_POSEVELOCITY_HPP_INCLUDED