/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: C:\Users\Marko\Documents\Development\morus_fuel_sensor\morus_uavcan_msgs\control\position_control\2051.Reference.uavcan
 */

#ifndef MORUS_UAVCAN_MSGS_CONTROL_POSITION_CONTROL_REFERENCE_HPP_INCLUDED
#define MORUS_UAVCAN_MSGS_CONTROL_POSITION_CONTROL_REFERENCE_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

#include <morus_uavcan_msgs\common\Pose.hpp>
#include <morus_uavcan_msgs\common\Twist.hpp>
#include <uavcan\Timestamp.hpp>

/******************************* Source text **********************************
#
# Message for setting position reference
#

uavcan.Timestamp	timestamp

morus_uavcan_msgs.common.Pose 	position
morus_uavcan_msgs.common.Twist 	velocity
morus_uavcan_msgs.common.Twist 	acceleration

float32 yaw_manual      #  [-1,1] , used in manual yaw mode
float32 throttle       #  [0,1] , used in manual height mode
******************************************************************************/

/********************* DSDL signature source definition ***********************
morus_uavcan_msgs.control.position_control.Reference
uavcan.Timestamp timestamp
morus_uavcan_msgs.common.Pose position
morus_uavcan_msgs.common.Twist velocity
morus_uavcan_msgs.common.Twist acceleration
saturated float32 yaw_manual
saturated float32 throttle
******************************************************************************/

#undef timestamp
#undef position
#undef velocity
#undef acceleration
#undef yaw_manual
#undef throttle

namespace morus_uavcan_msgs
{
namespace control
{
namespace position_control
{

template <int _tmpl>
struct UAVCAN_EXPORT Reference_
{
    typedef const Reference_<_tmpl>& ParameterType;
    typedef Reference_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::Timestamp timestamp;
        typedef ::morus_uavcan_msgs::common::Pose position;
        typedef ::morus_uavcan_msgs::common::Twist velocity;
        typedef ::morus_uavcan_msgs::common::Twist acceleration;
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > yaw_manual;
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > throttle;
    };

    enum
    {
        MinBitLen
            = FieldTypes::timestamp::MinBitLen
            + FieldTypes::position::MinBitLen
            + FieldTypes::velocity::MinBitLen
            + FieldTypes::acceleration::MinBitLen
            + FieldTypes::yaw_manual::MinBitLen
            + FieldTypes::throttle::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::timestamp::MaxBitLen
            + FieldTypes::position::MaxBitLen
            + FieldTypes::velocity::MaxBitLen
            + FieldTypes::acceleration::MaxBitLen
            + FieldTypes::yaw_manual::MaxBitLen
            + FieldTypes::throttle::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::timestamp >::Type timestamp;
    typename ::uavcan::StorageType< typename FieldTypes::position >::Type position;
    typename ::uavcan::StorageType< typename FieldTypes::velocity >::Type velocity;
    typename ::uavcan::StorageType< typename FieldTypes::acceleration >::Type acceleration;
    typename ::uavcan::StorageType< typename FieldTypes::yaw_manual >::Type yaw_manual;
    typename ::uavcan::StorageType< typename FieldTypes::throttle >::Type throttle;

    Reference_()
        : timestamp()
        , position()
        , velocity()
        , acceleration()
        , yaw_manual()
        , throttle()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<728 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 2051 };

    static const char* getDataTypeFullName()
    {
        return "morus_uavcan_msgs.control.position_control.Reference";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool Reference_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        timestamp == rhs.timestamp &&
        position == rhs.position &&
        velocity == rhs.velocity &&
        acceleration == rhs.acceleration &&
        yaw_manual == rhs.yaw_manual &&
        throttle == rhs.throttle;
}

template <int _tmpl>
bool Reference_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(timestamp, rhs.timestamp) &&
        ::uavcan::areClose(position, rhs.position) &&
        ::uavcan::areClose(velocity, rhs.velocity) &&
        ::uavcan::areClose(acceleration, rhs.acceleration) &&
        ::uavcan::areClose(yaw_manual, rhs.yaw_manual) &&
        ::uavcan::areClose(throttle, rhs.throttle);
}

template <int _tmpl>
int Reference_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::timestamp::encode(self.timestamp, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::position::encode(self.position, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::velocity::encode(self.velocity, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::acceleration::encode(self.acceleration, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::yaw_manual::encode(self.yaw_manual, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::throttle::encode(self.throttle, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int Reference_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::timestamp::decode(self.timestamp, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::position::decode(self.position, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::velocity::decode(self.velocity, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::acceleration::decode(self.acceleration, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::yaw_manual::decode(self.yaw_manual, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::throttle::decode(self.throttle, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature Reference_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0xD0381C680C83FB52ULL);

    FieldTypes::timestamp::extendDataTypeSignature(signature);
    FieldTypes::position::extendDataTypeSignature(signature);
    FieldTypes::velocity::extendDataTypeSignature(signature);
    FieldTypes::acceleration::extendDataTypeSignature(signature);
    FieldTypes::yaw_manual::extendDataTypeSignature(signature);
    FieldTypes::throttle::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef Reference_<0> Reference;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::morus_uavcan_msgs::control::position_control::Reference > _uavcan_gdtr_registrator_Reference;

}

} // Namespace position_control
} // Namespace control
} // Namespace morus_uavcan_msgs

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::morus_uavcan_msgs::control::position_control::Reference >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::morus_uavcan_msgs::control::position_control::Reference::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::morus_uavcan_msgs::control::position_control::Reference >::stream(Stream& s, ::morus_uavcan_msgs::control::position_control::Reference::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "timestamp: ";
    YamlStreamer< ::morus_uavcan_msgs::control::position_control::Reference::FieldTypes::timestamp >::stream(s, obj.timestamp, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "position: ";
    YamlStreamer< ::morus_uavcan_msgs::control::position_control::Reference::FieldTypes::position >::stream(s, obj.position, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "velocity: ";
    YamlStreamer< ::morus_uavcan_msgs::control::position_control::Reference::FieldTypes::velocity >::stream(s, obj.velocity, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "acceleration: ";
    YamlStreamer< ::morus_uavcan_msgs::control::position_control::Reference::FieldTypes::acceleration >::stream(s, obj.acceleration, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "yaw_manual: ";
    YamlStreamer< ::morus_uavcan_msgs::control::position_control::Reference::FieldTypes::yaw_manual >::stream(s, obj.yaw_manual, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "throttle: ";
    YamlStreamer< ::morus_uavcan_msgs::control::position_control::Reference::FieldTypes::throttle >::stream(s, obj.throttle, level + 1);
}

}

namespace morus_uavcan_msgs
{
namespace control
{
namespace position_control
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::morus_uavcan_msgs::control::position_control::Reference::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::morus_uavcan_msgs::control::position_control::Reference >::stream(s, obj, 0);
    return s;
}

} // Namespace position_control
} // Namespace control
} // Namespace morus_uavcan_msgs

#endif // MORUS_UAVCAN_MSGS_CONTROL_POSITION_CONTROL_REFERENCE_HPP_INCLUDED