/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: C:\Users\Marko\Documents\Development\morus_fuel_sensor\morus_uavcan_msgs\actuator\mm_motor\2024.PositionReferenceArray.uavcan
 */

#ifndef MORUS_UAVCAN_MSGS_ACTUATOR_MM_MOTOR_POSITIONREFERENCEARRAY_HPP_INCLUDED
#define MORUS_UAVCAN_MSGS_ACTUATOR_MM_MOTOR_POSITIONREFERENCEARRAY_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

#include <uavcan\Timestamp.hpp>

/******************************* Source text **********************************
#
# Message for controlling position of a electric motor
#

#
# Motor ID defines
#
uint8 FRONT = 1
uint8 RIGHT = 2
uint8 BACK = 3
uint8 LEFT = 4
uint8 NUMBER = 4

uavcan.Timestamp	timestamp
float32[4] position		# moving mass position setpoint [m]
******************************************************************************/

/********************* DSDL signature source definition ***********************
morus_uavcan_msgs.actuator.mm_motor.PositionReferenceArray
uavcan.Timestamp timestamp
saturated float32[4] position
******************************************************************************/

#undef timestamp
#undef position
#undef FRONT
#undef RIGHT
#undef BACK
#undef LEFT
#undef NUMBER

namespace morus_uavcan_msgs
{
namespace actuator
{
namespace mm_motor
{

template <int _tmpl>
struct UAVCAN_EXPORT PositionReferenceArray_
{
    typedef const PositionReferenceArray_<_tmpl>& ParameterType;
    typedef PositionReferenceArray_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > FRONT;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > RIGHT;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > BACK;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > LEFT;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > NUMBER;
    };

    struct FieldTypes
    {
        typedef ::uavcan::Timestamp timestamp;
        typedef ::uavcan::Array< ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate >, ::uavcan::ArrayModeStatic, 4 > position;
    };

    enum
    {
        MinBitLen
            = FieldTypes::timestamp::MinBitLen
            + FieldTypes::position::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::timestamp::MaxBitLen
            + FieldTypes::position::MaxBitLen
    };

    // Constants
    static const typename ::uavcan::StorageType< typename ConstantTypes::FRONT >::Type FRONT; // 1
    static const typename ::uavcan::StorageType< typename ConstantTypes::RIGHT >::Type RIGHT; // 2
    static const typename ::uavcan::StorageType< typename ConstantTypes::BACK >::Type BACK; // 3
    static const typename ::uavcan::StorageType< typename ConstantTypes::LEFT >::Type LEFT; // 4
    static const typename ::uavcan::StorageType< typename ConstantTypes::NUMBER >::Type NUMBER; // 4

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::timestamp >::Type timestamp;
    typename ::uavcan::StorageType< typename FieldTypes::position >::Type position;

    PositionReferenceArray_()
        : timestamp()
        , position()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<184 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 2024 };

    static const char* getDataTypeFullName()
    {
        return "morus_uavcan_msgs.actuator.mm_motor.PositionReferenceArray";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool PositionReferenceArray_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        timestamp == rhs.timestamp &&
        position == rhs.position;
}

template <int _tmpl>
bool PositionReferenceArray_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(timestamp, rhs.timestamp) &&
        ::uavcan::areClose(position, rhs.position);
}

template <int _tmpl>
int PositionReferenceArray_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::timestamp::encode(self.timestamp, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::position::encode(self.position, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int PositionReferenceArray_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::timestamp::decode(self.timestamp, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::position::decode(self.position, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature PositionReferenceArray_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0xD12BF7127923F755ULL);

    FieldTypes::timestamp::extendDataTypeSignature(signature);
    FieldTypes::position::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

template <int _tmpl>
const typename ::uavcan::StorageType< typename PositionReferenceArray_<_tmpl>::ConstantTypes::FRONT >::Type
    PositionReferenceArray_<_tmpl>::FRONT = 1U; // 1

template <int _tmpl>
const typename ::uavcan::StorageType< typename PositionReferenceArray_<_tmpl>::ConstantTypes::RIGHT >::Type
    PositionReferenceArray_<_tmpl>::RIGHT = 2U; // 2

template <int _tmpl>
const typename ::uavcan::StorageType< typename PositionReferenceArray_<_tmpl>::ConstantTypes::BACK >::Type
    PositionReferenceArray_<_tmpl>::BACK = 3U; // 3

template <int _tmpl>
const typename ::uavcan::StorageType< typename PositionReferenceArray_<_tmpl>::ConstantTypes::LEFT >::Type
    PositionReferenceArray_<_tmpl>::LEFT = 4U; // 4

template <int _tmpl>
const typename ::uavcan::StorageType< typename PositionReferenceArray_<_tmpl>::ConstantTypes::NUMBER >::Type
    PositionReferenceArray_<_tmpl>::NUMBER = 4U; // 4

/*
 * Final typedef
 */
typedef PositionReferenceArray_<0> PositionReferenceArray;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::morus_uavcan_msgs::actuator::mm_motor::PositionReferenceArray > _uavcan_gdtr_registrator_PositionReferenceArray;

}

} // Namespace mm_motor
} // Namespace actuator
} // Namespace morus_uavcan_msgs

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::PositionReferenceArray >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::morus_uavcan_msgs::actuator::mm_motor::PositionReferenceArray::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::PositionReferenceArray >::stream(Stream& s, ::morus_uavcan_msgs::actuator::mm_motor::PositionReferenceArray::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "timestamp: ";
    YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::PositionReferenceArray::FieldTypes::timestamp >::stream(s, obj.timestamp, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "position: ";
    YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::PositionReferenceArray::FieldTypes::position >::stream(s, obj.position, level + 1);
}

}

namespace morus_uavcan_msgs
{
namespace actuator
{
namespace mm_motor
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::morus_uavcan_msgs::actuator::mm_motor::PositionReferenceArray::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::PositionReferenceArray >::stream(s, obj, 0);
    return s;
}

} // Namespace mm_motor
} // Namespace actuator
} // Namespace morus_uavcan_msgs

#endif // MORUS_UAVCAN_MSGS_ACTUATOR_MM_MOTOR_POSITIONREFERENCEARRAY_HPP_INCLUDED