/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: C:\Users\Marko\Documents\Development\morus_fuel_sensor\morus_uavcan_msgs\actuator\mm_motor\2021.Status.uavcan
 */

#ifndef MORUS_UAVCAN_MSGS_ACTUATOR_MM_MOTOR_STATUS_HPP_INCLUDED
#define MORUS_UAVCAN_MSGS_ACTUATOR_MM_MOTOR_STATUS_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

#include <uavcan\Timestamp.hpp>

/******************************* Source text **********************************
#
# moving mass feedback, if available.
# Unknown fields should be set to NAN.
#

#
# Motor ID defines
#
uint8 FRONT = 1
uint8 RIGHT = 2
uint8 BACK = 3
uint8 LEFT = 4
uint8 ALL = 0

uavcan.Timestamp timestamp

uint8 actuator_id         # 1 - front, 2 - right, 3 - back, 4-left

float32 position_M        # measured position [m]
int16 speed_M           # measured speed [rpm]
float32 temperature_M     # temperature [celsius degrees]

float32 position_S        # position reference [m]
******************************************************************************/

/********************* DSDL signature source definition ***********************
morus_uavcan_msgs.actuator.mm_motor.Status
uavcan.Timestamp timestamp
saturated uint8 actuator_id
saturated float32 position_M
saturated int16 speed_M
saturated float32 temperature_M
saturated float32 position_S
******************************************************************************/

#undef timestamp
#undef actuator_id
#undef position_M
#undef speed_M
#undef temperature_M
#undef position_S
#undef FRONT
#undef RIGHT
#undef BACK
#undef LEFT
#undef ALL

namespace morus_uavcan_msgs
{
namespace actuator
{
namespace mm_motor
{

template <int _tmpl>
struct UAVCAN_EXPORT Status_
{
    typedef const Status_<_tmpl>& ParameterType;
    typedef Status_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > FRONT;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > RIGHT;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > BACK;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > LEFT;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > ALL;
    };

    struct FieldTypes
    {
        typedef ::uavcan::Timestamp timestamp;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > actuator_id;
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > position_M;
        typedef ::uavcan::IntegerSpec< 16, ::uavcan::SignednessSigned, ::uavcan::CastModeSaturate > speed_M;
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > temperature_M;
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > position_S;
    };

    enum
    {
        MinBitLen
            = FieldTypes::timestamp::MinBitLen
            + FieldTypes::actuator_id::MinBitLen
            + FieldTypes::position_M::MinBitLen
            + FieldTypes::speed_M::MinBitLen
            + FieldTypes::temperature_M::MinBitLen
            + FieldTypes::position_S::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::timestamp::MaxBitLen
            + FieldTypes::actuator_id::MaxBitLen
            + FieldTypes::position_M::MaxBitLen
            + FieldTypes::speed_M::MaxBitLen
            + FieldTypes::temperature_M::MaxBitLen
            + FieldTypes::position_S::MaxBitLen
    };

    // Constants
    static const typename ::uavcan::StorageType< typename ConstantTypes::FRONT >::Type FRONT; // 1
    static const typename ::uavcan::StorageType< typename ConstantTypes::RIGHT >::Type RIGHT; // 2
    static const typename ::uavcan::StorageType< typename ConstantTypes::BACK >::Type BACK; // 3
    static const typename ::uavcan::StorageType< typename ConstantTypes::LEFT >::Type LEFT; // 4
    static const typename ::uavcan::StorageType< typename ConstantTypes::ALL >::Type ALL; // 0

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::timestamp >::Type timestamp;
    typename ::uavcan::StorageType< typename FieldTypes::actuator_id >::Type actuator_id;
    typename ::uavcan::StorageType< typename FieldTypes::position_M >::Type position_M;
    typename ::uavcan::StorageType< typename FieldTypes::speed_M >::Type speed_M;
    typename ::uavcan::StorageType< typename FieldTypes::temperature_M >::Type temperature_M;
    typename ::uavcan::StorageType< typename FieldTypes::position_S >::Type position_S;

    Status_()
        : timestamp()
        , actuator_id()
        , position_M()
        , speed_M()
        , temperature_M()
        , position_S()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<176 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 2021 };

    static const char* getDataTypeFullName()
    {
        return "morus_uavcan_msgs.actuator.mm_motor.Status";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool Status_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        timestamp == rhs.timestamp &&
        actuator_id == rhs.actuator_id &&
        position_M == rhs.position_M &&
        speed_M == rhs.speed_M &&
        temperature_M == rhs.temperature_M &&
        position_S == rhs.position_S;
}

template <int _tmpl>
bool Status_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(timestamp, rhs.timestamp) &&
        ::uavcan::areClose(actuator_id, rhs.actuator_id) &&
        ::uavcan::areClose(position_M, rhs.position_M) &&
        ::uavcan::areClose(speed_M, rhs.speed_M) &&
        ::uavcan::areClose(temperature_M, rhs.temperature_M) &&
        ::uavcan::areClose(position_S, rhs.position_S);
}

template <int _tmpl>
int Status_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::timestamp::encode(self.timestamp, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::actuator_id::encode(self.actuator_id, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::position_M::encode(self.position_M, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::speed_M::encode(self.speed_M, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::temperature_M::encode(self.temperature_M, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::position_S::encode(self.position_S, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int Status_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::timestamp::decode(self.timestamp, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::actuator_id::decode(self.actuator_id, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::position_M::decode(self.position_M, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::speed_M::decode(self.speed_M, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::temperature_M::decode(self.temperature_M, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::position_S::decode(self.position_S, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature Status_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x507B204A1E6598E4ULL);

    FieldTypes::timestamp::extendDataTypeSignature(signature);
    FieldTypes::actuator_id::extendDataTypeSignature(signature);
    FieldTypes::position_M::extendDataTypeSignature(signature);
    FieldTypes::speed_M::extendDataTypeSignature(signature);
    FieldTypes::temperature_M::extendDataTypeSignature(signature);
    FieldTypes::position_S::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

template <int _tmpl>
const typename ::uavcan::StorageType< typename Status_<_tmpl>::ConstantTypes::FRONT >::Type
    Status_<_tmpl>::FRONT = 1U; // 1

template <int _tmpl>
const typename ::uavcan::StorageType< typename Status_<_tmpl>::ConstantTypes::RIGHT >::Type
    Status_<_tmpl>::RIGHT = 2U; // 2

template <int _tmpl>
const typename ::uavcan::StorageType< typename Status_<_tmpl>::ConstantTypes::BACK >::Type
    Status_<_tmpl>::BACK = 3U; // 3

template <int _tmpl>
const typename ::uavcan::StorageType< typename Status_<_tmpl>::ConstantTypes::LEFT >::Type
    Status_<_tmpl>::LEFT = 4U; // 4

template <int _tmpl>
const typename ::uavcan::StorageType< typename Status_<_tmpl>::ConstantTypes::ALL >::Type
    Status_<_tmpl>::ALL = 0U; // 0

/*
 * Final typedef
 */
typedef Status_<0> Status;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::morus_uavcan_msgs::actuator::mm_motor::Status > _uavcan_gdtr_registrator_Status;

}

} // Namespace mm_motor
} // Namespace actuator
} // Namespace morus_uavcan_msgs

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::Status >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::morus_uavcan_msgs::actuator::mm_motor::Status::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::Status >::stream(Stream& s, ::morus_uavcan_msgs::actuator::mm_motor::Status::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "timestamp: ";
    YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::Status::FieldTypes::timestamp >::stream(s, obj.timestamp, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "actuator_id: ";
    YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::Status::FieldTypes::actuator_id >::stream(s, obj.actuator_id, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "position_M: ";
    YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::Status::FieldTypes::position_M >::stream(s, obj.position_M, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "speed_M: ";
    YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::Status::FieldTypes::speed_M >::stream(s, obj.speed_M, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "temperature_M: ";
    YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::Status::FieldTypes::temperature_M >::stream(s, obj.temperature_M, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "position_S: ";
    YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::Status::FieldTypes::position_S >::stream(s, obj.position_S, level + 1);
}

}

namespace morus_uavcan_msgs
{
namespace actuator
{
namespace mm_motor
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::morus_uavcan_msgs::actuator::mm_motor::Status::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::Status >::stream(s, obj, 0);
    return s;
}

} // Namespace mm_motor
} // Namespace actuator
} // Namespace morus_uavcan_msgs

#endif // MORUS_UAVCAN_MSGS_ACTUATOR_MM_MOTOR_STATUS_HPP_INCLUDED