/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: C:\Users\Marko\Documents\Development\morus_fuel_sensor\morus_uavcan_msgs\actuator\mm_motor\2023.VelocityReference.uavcan
 */

#ifndef MORUS_UAVCAN_MSGS_ACTUATOR_MM_MOTOR_VELOCITYREFERENCE_HPP_INCLUDED
#define MORUS_UAVCAN_MSGS_ACTUATOR_MM_MOTOR_VELOCITYREFERENCE_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Message for controlling velocity of a electric motor
#

#
# Motor ID defines
#
uint8 FRONT = 1
uint8 RIGHT = 2
uint8 BACK = 3
uint8 LEFT = 4
uint8 ALL = 0

uint8 motor_id			# id of the electric motor 1-front, 2-right, 3-back, 4-left, 0 - all motors
float32 velocity		# motor velocity [rad/s]
******************************************************************************/

/********************* DSDL signature source definition ***********************
morus_uavcan_msgs.actuator.mm_motor.VelocityReference
saturated uint8 motor_id
saturated float32 velocity
******************************************************************************/

#undef motor_id
#undef velocity
#undef FRONT
#undef RIGHT
#undef BACK
#undef LEFT
#undef ALL

namespace morus_uavcan_msgs
{
namespace actuator
{
namespace mm_motor
{

template <int _tmpl>
struct UAVCAN_EXPORT VelocityReference_
{
    typedef const VelocityReference_<_tmpl>& ParameterType;
    typedef VelocityReference_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > FRONT;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > RIGHT;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > BACK;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > LEFT;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > ALL;
    };

    struct FieldTypes
    {
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > motor_id;
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > velocity;
    };

    enum
    {
        MinBitLen
            = FieldTypes::motor_id::MinBitLen
            + FieldTypes::velocity::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::motor_id::MaxBitLen
            + FieldTypes::velocity::MaxBitLen
    };

    // Constants
    static const typename ::uavcan::StorageType< typename ConstantTypes::FRONT >::Type FRONT; // 1
    static const typename ::uavcan::StorageType< typename ConstantTypes::RIGHT >::Type RIGHT; // 2
    static const typename ::uavcan::StorageType< typename ConstantTypes::BACK >::Type BACK; // 3
    static const typename ::uavcan::StorageType< typename ConstantTypes::LEFT >::Type LEFT; // 4
    static const typename ::uavcan::StorageType< typename ConstantTypes::ALL >::Type ALL; // 0

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::motor_id >::Type motor_id;
    typename ::uavcan::StorageType< typename FieldTypes::velocity >::Type velocity;

    VelocityReference_()
        : motor_id()
        , velocity()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<40 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 2023 };

    static const char* getDataTypeFullName()
    {
        return "morus_uavcan_msgs.actuator.mm_motor.VelocityReference";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool VelocityReference_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        motor_id == rhs.motor_id &&
        velocity == rhs.velocity;
}

template <int _tmpl>
bool VelocityReference_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(motor_id, rhs.motor_id) &&
        ::uavcan::areClose(velocity, rhs.velocity);
}

template <int _tmpl>
int VelocityReference_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::motor_id::encode(self.motor_id, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::velocity::encode(self.velocity, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int VelocityReference_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::motor_id::decode(self.motor_id, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::velocity::decode(self.velocity, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature VelocityReference_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x569C88A84479EC26ULL);

    FieldTypes::motor_id::extendDataTypeSignature(signature);
    FieldTypes::velocity::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

template <int _tmpl>
const typename ::uavcan::StorageType< typename VelocityReference_<_tmpl>::ConstantTypes::FRONT >::Type
    VelocityReference_<_tmpl>::FRONT = 1U; // 1

template <int _tmpl>
const typename ::uavcan::StorageType< typename VelocityReference_<_tmpl>::ConstantTypes::RIGHT >::Type
    VelocityReference_<_tmpl>::RIGHT = 2U; // 2

template <int _tmpl>
const typename ::uavcan::StorageType< typename VelocityReference_<_tmpl>::ConstantTypes::BACK >::Type
    VelocityReference_<_tmpl>::BACK = 3U; // 3

template <int _tmpl>
const typename ::uavcan::StorageType< typename VelocityReference_<_tmpl>::ConstantTypes::LEFT >::Type
    VelocityReference_<_tmpl>::LEFT = 4U; // 4

template <int _tmpl>
const typename ::uavcan::StorageType< typename VelocityReference_<_tmpl>::ConstantTypes::ALL >::Type
    VelocityReference_<_tmpl>::ALL = 0U; // 0

/*
 * Final typedef
 */
typedef VelocityReference_<0> VelocityReference;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::morus_uavcan_msgs::actuator::mm_motor::VelocityReference > _uavcan_gdtr_registrator_VelocityReference;

}

} // Namespace mm_motor
} // Namespace actuator
} // Namespace morus_uavcan_msgs

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::VelocityReference >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::morus_uavcan_msgs::actuator::mm_motor::VelocityReference::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::VelocityReference >::stream(Stream& s, ::morus_uavcan_msgs::actuator::mm_motor::VelocityReference::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "motor_id: ";
    YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::VelocityReference::FieldTypes::motor_id >::stream(s, obj.motor_id, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "velocity: ";
    YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::VelocityReference::FieldTypes::velocity >::stream(s, obj.velocity, level + 1);
}

}

namespace morus_uavcan_msgs
{
namespace actuator
{
namespace mm_motor
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::morus_uavcan_msgs::actuator::mm_motor::VelocityReference::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::morus_uavcan_msgs::actuator::mm_motor::VelocityReference >::stream(s, obj, 0);
    return s;
}

} // Namespace mm_motor
} // Namespace actuator
} // Namespace morus_uavcan_msgs

#endif // MORUS_UAVCAN_MSGS_ACTUATOR_MM_MOTOR_VELOCITYREFERENCE_HPP_INCLUDED