/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: C:\Users\Marko\Documents\Development\morus_fuel_sensor\morus_uavcan_msgs\common\Vector3.uavcan
 */

#ifndef MORUS_UAVCAN_MSGS_COMMON_VECTOR3_HPP_INCLUDED
#define MORUS_UAVCAN_MSGS_COMMON_VECTOR3_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Msg that contains the position of a point in free space
#

float32 x
float32 y
float32 z
******************************************************************************/

/********************* DSDL signature source definition ***********************
morus_uavcan_msgs.common.Vector3
saturated float32 x
saturated float32 y
saturated float32 z
******************************************************************************/

#undef x
#undef y
#undef z

namespace morus_uavcan_msgs
{
namespace common
{

template <int _tmpl>
struct UAVCAN_EXPORT Vector3_
{
    typedef const Vector3_<_tmpl>& ParameterType;
    typedef Vector3_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > x;
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > y;
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > z;
    };

    enum
    {
        MinBitLen
            = FieldTypes::x::MinBitLen
            + FieldTypes::y::MinBitLen
            + FieldTypes::z::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::x::MaxBitLen
            + FieldTypes::y::MaxBitLen
            + FieldTypes::z::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::x >::Type x;
    typename ::uavcan::StorageType< typename FieldTypes::y >::Type y;
    typename ::uavcan::StorageType< typename FieldTypes::z >::Type z;

    Vector3_()
        : x()
        , y()
        , z()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<96 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    // This type has no default data type ID

    static const char* getDataTypeFullName()
    {
        return "morus_uavcan_msgs.common.Vector3";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool Vector3_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        x == rhs.x &&
        y == rhs.y &&
        z == rhs.z;
}

template <int _tmpl>
bool Vector3_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(x, rhs.x) &&
        ::uavcan::areClose(y, rhs.y) &&
        ::uavcan::areClose(z, rhs.z);
}

template <int _tmpl>
int Vector3_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::x::encode(self.x, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::y::encode(self.y, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::z::encode(self.z, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int Vector3_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::x::decode(self.x, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::y::decode(self.y, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::z::decode(self.z, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature Vector3_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x91A3C58DAACB5731ULL);

    FieldTypes::x::extendDataTypeSignature(signature);
    FieldTypes::y::extendDataTypeSignature(signature);
    FieldTypes::z::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef Vector3_<0> Vector3;

// No default registration

} // Namespace common
} // Namespace morus_uavcan_msgs

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::morus_uavcan_msgs::common::Vector3 >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::morus_uavcan_msgs::common::Vector3::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::morus_uavcan_msgs::common::Vector3 >::stream(Stream& s, ::morus_uavcan_msgs::common::Vector3::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "x: ";
    YamlStreamer< ::morus_uavcan_msgs::common::Vector3::FieldTypes::x >::stream(s, obj.x, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "y: ";
    YamlStreamer< ::morus_uavcan_msgs::common::Vector3::FieldTypes::y >::stream(s, obj.y, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "z: ";
    YamlStreamer< ::morus_uavcan_msgs::common::Vector3::FieldTypes::z >::stream(s, obj.z, level + 1);
}

}

namespace morus_uavcan_msgs
{
namespace common
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::morus_uavcan_msgs::common::Vector3::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::morus_uavcan_msgs::common::Vector3 >::stream(s, obj, 0);
    return s;
}

} // Namespace common
} // Namespace morus_uavcan_msgs

#endif // MORUS_UAVCAN_MSGS_COMMON_VECTOR3_HPP_INCLUDED